version: "3"
services:
  app:
    user: $uid:$gid
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
  db:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=supersecretpassword
    ports:
      - 8082:80
    depends_on:
      - db
